apiVersion: v1
kind: ConfigMap
metadata:
  name: dog1-configmap
  namespace: deviceshifu
  labels:
    app: deviceshifu-dog1
    workspace_id: "cdef6dc9-678e-4a15-91ac-dbb36f61528b"
    workspace_name: "demo"
data:
  driverProperties: |
    driverSku: Robot Dog MQTT Device
    driverImage: robot-dog-mqtt:latest
---

apiVersion: shifu.edgenesis.io/v1alpha1
kind: EdgeDevice
metadata:
  name: edgedevice-dog1
  namespace: devices
  labels:
    app: deviceshifu-dog1
    workspace_id: "cdef6dc9-678e-4a15-91ac-dbb36f61528b"
    workspace_name: "demo"
  annotations:
    workspace.id: "cdef6dc9-678e-4a15-91ac-dbb36f61528b"
    workspace.name: "demo"
    template.id: "robotdog-mqtt-v1"
spec:
  sku: "Robot Dog MQTT Device"
  connection: Ethernet
  address: "192.168.4.101"
  protocol: UDP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deviceshifu-dog1
    workspace_id: "cdef6dc9-678e-4a15-91ac-dbb36f61528b"
  name: deviceshifu-dog1
  namespace: deviceshifu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deviceshifu-dog1
  template:
    metadata:
      labels:
        app: deviceshifu-dog1
        workspace_id: "cdef6dc9-678e-4a15-91ac-dbb36f61528b"
    spec:
      containers:
        - image: edgenesis/deeprobotics-robotdog-mqtt:v0.0.2
          name: deviceshifu-dog1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: deviceshifu-config
              mountPath: "/etc/edgedevice/config"
              readOnly: true
          env:
            - name: EDGEDEVICE_NAME
              value: "edgedevice-dog1"
            - name: EDGEDEVICE_NAMESPACE
              value: "devices"
            - name: MQTT_BROKER_ADDRESS
              value: ""
            # No MQTT authentication configured in workspace
            
            - name: CONFIG_MOUNT_PATH
              value: "/etc/edgedevice/config"
            - name: DATA_FETCH_INTERVAL_SECONDS
              value: "1"
      volumes:
        - name: deviceshifu-config
          configMap:
            name: dog1-configmap
      serviceAccountName: edgedevice-sa
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deviceshifu-dog1
    workspace_id: "cdef6dc9-678e-4a15-91ac-dbb36f61528b"
  name: deviceshifu-dog1
  namespace: deviceshifu
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app: deviceshifu-dog1
  type: ClusterIP
